[theme]
base = "dark"
primaryColor = "#FF4B4B"
[server]
runOnSave = true
enableStaticServing = true
[ui]
hideTopBar = true
[logger]

# Level of logging for Streamlit's internal logger: "error", "warning",
# "info", or "debug".
# Default: "info"
level = "info"
[client]
showErrorDetails = "full"